"""
Animated Buddy - reads animations composed of STEPS
======================================================
Each animation in animations.json (generated by organizer.py v3) is a list
of "steps". Each step is one of two cases:

- {"mode": "alone", "file": "body.png"}
    -> shows that frame in isolation, nothing overlaid.

- {"mode": "combined", "file": "body.png", "extra_file": "mouth.png",
   "offset_x": 120, "offset_y": 80}
    -> shows "file" (the base) with "extra_file" (e.g. the mouth) drawn on
       top, at the position given by the offset.

This lets a single animation mix moments where the body stays still alone
(pauses) with moments where the body appears combined with an overlaid
mouth (talking) - without having to duplicate the whole body in every
talking frame.

Each animation also carries a free-text "description" from the JSON, used
here just to print to the console when switching animations - handy for
debugging/understanding what each state represents, and you can reuse that
text elsewhere in your assistant (e.g. logging).
"""
import sys
import os
import json
import random
import signal
import time
import datetime
import numpy as np
from PyQt5.QtCore import Qt, QPoint, QTimer, QThread, pyqtSignal
from PyQt5.QtGui import QPixmap, QImage, QPainter, QFontMetrics
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QLineEdit, QMenu

import states
import language_learning
from brain import OllamaBrain
from voice import VoiceAssistant
from todoist import TodoistClient, LIST_TASKS_SCHEMA, ADD_TASK_SCHEMA, MOVE_TASK_SCHEMA
from google_auth import GoogleOAuthClient
from gcal import GoogleCalendarClient, LIST_EVENTS_SCHEMA, CREATE_EVENT_SCHEMA
from gmail import GmailClient, LIST_RECENT_EMAILS_SCHEMA, SEARCH_EMAILS_SCHEMA, READ_EMAIL_SCHEMA

IMAGES_FOLDER = "imgs"
ANIMATIONS_FILE = os.path.join(IMAGES_FOLDER, "animations.json")

# Background color to remove (adjust if needed) and tolerance (0-255)
BACKGROUND_COLOR = (0, 255, 255)  # cyan
TOLERANCE = 40

# Duration (in seconds) of the smooth transition when switching animation/pose
SWITCH_TRANSITION_DURATION = 0.22

# Area reserved (within the monkey's own window) for the speech bubble.
# The height is the base (short); for long replies it grows up to the max.
BUBBLE_WIDTH = 260
BUBBLE_HEIGHT = 70
BUBBLE_HEIGHT_MAX = 280

# How often to check Todoist for due/overdue tasks and proactively remind
# the user (only announced while idle - see _on_todoist_check_result).
REMINDER_POLL_INTERVAL_MS = 5 * 60 * 1000

# How often to check Google Calendar for meetings starting soon, and how
# far ahead to look (only announced while idle - see _on_calendar_check_result).
CALENDAR_POLL_INTERVAL_MS = 2 * 60 * 1000
CALENDAR_LOOKAHEAD_MINUTES = 15

# How often the monkey drops a short German tip (word or grammar rule) out
# of the blue - a random interval within this range, re-rolled after each
# tip (see _schedule_next_language_tip / _language_tip_tick), so it doesn't
# feel like a mechanical fixed-period alarm.
LANGUAGE_TIP_MIN_INTERVAL_MS = 5 * 60 * 1000
LANGUAGE_TIP_MAX_INTERVAL_MS = 10 * 60 * 1000
# If the monkey isn't idle when a tip comes due (mid-conversation, etc.),
# don't lose the tick - just retry again shortly instead of waiting out a
# full 5-10min interval before trying again.
LANGUAGE_TIP_RETRY_INTERVAL_MS = 30 * 1000

# Queue file that notify_claude_hook.py appends to (see that file) - wired
# up as the command for Claude Code's Notification/Stop hooks in
# ~/.claude/settings.json, so the monkey can announce when Claude needs a
# permission decision, is waiting idle, or finishes a reply. Polled instead
# of pushed to since Claude Code hooks are short-lived one-shot processes
# with no persistent connection back to this long-running app.
NOTIFY_QUEUE_FILE = os.path.expanduser("~/.cache/buddy-assistant/claude_notifications.jsonl")
NOTIFY_POLL_INTERVAL_MS = 3 * 1000
# Entries older than this are dropped without being announced - avoids the
# monkey dumping a stale backlog of notifications right after it starts up.
NOTIFY_MAX_AGE_SECONDS = 120

# Only offer the Todoist/Calendar tools to the model when the message looks
# task/event-related - a small model like llama3.2:3b otherwise tends to
# reach for a tool even for plain small talk (see brain.py's tool_trigger_keywords).
TODOIST_KEYWORDS = (
    "tarefa", "tarefas", "pendencia", "pendencias", "pendente", "pendentes",
    "afazer", "afazeres", "lembrar", "lembrete", "lembra", "anota", "anote",
    "anotar", "adiciona", "adicione", "adicionar", "atrasad", "todoist",
    "compromisso", "compromissos", "fazer hoje", "minha lista", "projeto",
)

CALENDAR_KEYWORDS = (
    "agenda", "calendario", "evento", "eventos", "reuniao", "reunioes",
    "marcar", "marca", "horario", "google calendar",
)

GMAIL_KEYWORDS = (
    "email", "e-mail", "emails", "e-mails", "gmail", "caixa de entrada",
    "inbox", "mensagem", "mensagens",
)


def remove_background(image_path, background_color=BACKGROUND_COLOR, tolerance=TOLERANCE):
    """Loads an image and returns a QPixmap with the background made
    transparent, using a tolerance band instead of an exact binary mask.
    Vectorized with numpy - the pure-Python pixel-by-pixel version took
    minutes to prepare all the frames for ~50 animations."""
    image = QImage(image_path)
    if image.isNull():
        return None
    image = image.convertToFormat(QImage.Format_ARGB32)

    width, height = image.width(), image.height()
    bytes_per_line = image.bytesPerLine()
    pointer = image.bits()
    pointer.setsize(bytes_per_line * height)
    raw = np.frombuffer(pointer, dtype=np.uint8).reshape((height, bytes_per_line))
    pixels = raw[:, : width * 4].reshape((height, width, 4)).copy()

    # Format_ARGB32 stores each pixel in memory (little-endian) as B, G, R, A
    b, g, r = pixels[..., 0].astype(np.int16), pixels[..., 1].astype(np.int16), pixels[..., 2].astype(np.int16)
    r0, g0, b0 = background_color
    mask = (
        (np.abs(r - r0) <= tolerance)
        & (np.abs(g - g0) <= tolerance)
        & (np.abs(b - b0) <= tolerance)
    )
    pixels[mask] = 0

    result = QImage(pixels.tobytes(), width, height, width * 4, QImage.Format_ARGB32)
    return QPixmap.fromImage(result.copy())


class AskWorker(QThread):
    """Runs OllamaBrain.ask() off the UI thread so the animations don't
    freeze while the model is thinking."""
    result = pyqtSignal(str)
    error = pyqtSignal(str)

    def __init__(self, brain, text):
        super().__init__()
        self.brain = brain
        self.text = text

    def run(self):
        try:
            reply = self.brain.ask(self.text)
            self.result.emit(reply)
        except Exception as error:
            self.error.emit(str(error))


class TodoistCheckWorker(QThread):
    """Polls Todoist for due/overdue tasks off the UI thread."""
    result = pyqtSignal(list)
    error = pyqtSignal(str)

    def __init__(self, todoist_client):
        super().__init__()
        self.todoist_client = todoist_client

    def run(self):
        try:
            tasks = self.todoist_client.list_tasks(when="today_or_overdue")
            self.result.emit(tasks)
        except Exception as error:
            self.error.emit(str(error))


class CalendarCheckWorker(QThread):
    """Polls Google Calendar for events starting soon, off the UI thread."""
    result = pyqtSignal(list)
    error = pyqtSignal(str)

    def __init__(self, calendar_client):
        super().__init__()
        self.calendar_client = calendar_client

    def run(self):
        try:
            events = self.calendar_client.list_events(when="upcoming")
            self.result.emit(events)
        except Exception as error:
            self.error.emit(str(error))


class AnimatedBuddy(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint | Qt.SubWindow)
        self.setAttribute(Qt.WA_TranslucentBackground)

        self.label = QLabel(self)

        self.animation_definitions = self.load_definitions()
        self.file_pixmap_cache = {}   # file_name -> QPixmap with background removed
        self.ready_frames = {}        # animation_name -> [QPixmap, QPixmap, ...]

        self.prepare_all_frames()

        self.current_animation = None
        self.frame_index = 0
        self.next_animation_after_finish = None
        self.force_once = False
        self._on_finish_callback = None

        self._pm_previous = None
        self._pm_next = None
        self._segment_start = 0.0
        self._segment_duration = 0.0

        self.timer = QTimer(self)
        self.timer.timeout.connect(self._render_tick)
        self.timer.start(30)  # ~33fps of interpolation, independent of each animation's fps

        self.canvas_size = self.calculate_canvas_size()
        sprite_width, sprite_height = self.canvas_size
        self._window_width = max(sprite_width, BUBBLE_WIDTH)
        self._current_bubble_height = BUBBLE_HEIGHT
        window_height = sprite_height + BUBBLE_HEIGHT
        self.setGeometry(100, 100, self._window_width, window_height)

        sprite_x = (self._window_width - sprite_width) // 2
        self.label.setGeometry(sprite_x, BUBBLE_HEIGHT, sprite_width, sprite_height)

        # Speech bubble: widgets that are children of the SAME window as the
        # monkey (instead of a separate top-level window) - an independent
        # frameless+translucent QWidget turned out to be unreliable to
        # composite on this machine (it would sometimes just not paint).
        bubble_style = (
            "background-color: rgba(255, 255, 255, 235); border-radius: 10px;"
            "padding: 8px; font-size: 13px; color: #222;"
        )

        self.bubble_label = QLabel(self)
        self.bubble_label.setGeometry(0, 0, self._window_width, BUBBLE_HEIGHT - 12)
        self.bubble_label.setWordWrap(True)
        self.bubble_label.setAlignment(Qt.AlignCenter)
        self.bubble_label.setStyleSheet(bubble_style)
        self.bubble_label.hide()

        self.bubble_input = QLineEdit(self)
        self.bubble_input.setGeometry(0, 0, self._window_width, BUBBLE_HEIGHT - 12)
        self.bubble_input.setPlaceholderText("Talk to the monkey...")
        self.bubble_input.setStyleSheet(bubble_style)
        self.bubble_input.returnPressed.connect(self._send_from_input)
        self.bubble_input.hide()

        self.drag_position = QPoint()
        self._dragged = False

        # ---------------- Assistant behavior ----------------
        self.current_state = "IDLE"
        self._worker = None

        self.todoist = TodoistClient()
        self.google_auth = GoogleOAuthClient()  # shared login for Calendar + Gmail
        self.calendar = GoogleCalendarClient(auth=self.google_auth)
        self.gmail = GmailClient(auth=self.google_auth)
        self.brain = OllamaBrain(
            tools={
                "list_tasks": {"schema": LIST_TASKS_SCHEMA, "function": self.todoist.list_tasks},
                "add_task": {"schema": ADD_TASK_SCHEMA, "function": self.todoist.add_task},
                "move_task_to_project": {"schema": MOVE_TASK_SCHEMA, "function": self.todoist.move_task_to_project},
                "list_events": {"schema": LIST_EVENTS_SCHEMA, "function": self.calendar.list_events},
                "create_event": {"schema": CREATE_EVENT_SCHEMA, "function": self.calendar.create_event},
                "list_recent_emails": {"schema": LIST_RECENT_EMAILS_SCHEMA, "function": self.gmail.list_recent_emails},
                "search_emails": {"schema": SEARCH_EMAILS_SCHEMA, "function": self.gmail.search_emails},
                "read_email": {"schema": READ_EMAIL_SCHEMA, "function": self.gmail.read_email},
            },
            tool_trigger_keywords=TODOIST_KEYWORDS + CALENDAR_KEYWORDS + GMAIL_KEYWORDS,
        )
        self.voice = VoiceAssistant()

        self.voice.recording_started.connect(lambda: self.enter_state("LISTENING"))
        self.voice.transcription_ready.connect(self._on_transcription)
        self.voice.speech_finished.connect(self._on_speech_finished)

        self._reminded_task_ids = set()
        self._reminder_worker = None
        self._reminder_timer = QTimer(self)
        self._reminder_timer.timeout.connect(self._check_todoist_reminders)
        if self.todoist.is_configured():
            self._reminder_timer.start(REMINDER_POLL_INTERVAL_MS)
            QTimer.singleShot(30000, self._check_todoist_reminders)

        self._reminded_event_ids = set()
        self._calendar_worker = None
        self._calendar_timer = QTimer(self)
        self._calendar_timer.timeout.connect(self._check_calendar_reminders)
        if self.calendar.is_configured() and self.calendar.is_authenticated():
            self._calendar_timer.start(CALENDAR_POLL_INTERVAL_MS)
            QTimer.singleShot(45000, self._check_calendar_reminders)

        self._schedule_next_language_tip()

        # Start reading from the current end of the queue file, not its
        # start - otherwise restarting the monkey would replay every old
        # Claude Code notification ever queued.
        self._notify_queue_offset = self._notify_queue_size()
        self._notify_timer = QTimer(self)
        self._notify_timer.timeout.connect(self._check_claude_notifications)
        self._notify_timer.start(NOTIFY_POLL_INTERVAL_MS)

        if not self.ready_frames:
            print(f"No animations found in {ANIMATIONS_FILE}. "
                  f"Generate that file with organizer.py.")
        else:
            self.voice.start()
            self.enter_state("GREETING")

    # ------------------------------------------------------------------
    # Assistant control (states <-> animations)
    # ------------------------------------------------------------------
    def _play_state(self, name):
        if name in self.ready_frames:
            self.play_animation(name, next_after_finish=name)

    def _schedule_next_idle_gesture(self):
        interval_ms = random.randint(4000, 9000)
        QTimer.singleShot(interval_ms, self._idle_gesture_tick)

    def _idle_gesture_tick(self):
        if self.current_state != "IDLE":
            return
        gesture = random.choice(states.IDLE_GESTURES)
        self.play_animation(
            gesture,
            next_after_finish=states.IDLE_BASE,
            once=True,
            on_finish_callback=self._schedule_next_idle_gesture,
        )

    def enter_state(self, state, text=None):
        self.current_state = state

        if state == "IDLE":
            self._hide_bubble()
            self._play_state(states.IDLE_BASE)
            self._schedule_next_idle_gesture()

        elif state == "GREETING":
            self._play_state(random.choice(states.GREETING_POOL))
            QTimer.singleShot(3000, self._on_greeting_finished)

        elif state == "LISTENING":
            self._hide_bubble()
            self._play_state(random.choice(states.LISTENING_POOL))

        elif state == "THINKING":
            self._play_state(random.choice(states.THINKING_POOL))

        elif state == "TALKING":
            pool = states.choose_pool_for_reply(text)
            self._play_state(random.choice(pool))
            self._show_bubble_text(text)
            if self.voice.muted:
                duration_ms = max(1500, int(len(text or "") * 55))
                QTimer.singleShot(duration_ms, self._on_speech_finished)
            else:
                self.voice.speak(text)

    def process_question(self, text):
        text = (text or "").strip()
        if not text:
            return
        self.enter_state("THINKING")
        self._worker = AskWorker(self.brain, text)
        self._worker.result.connect(lambda r: self.enter_state("TALKING", text=r))
        self._worker.error.connect(self._on_reply_error)
        self._worker.start()

    def _on_reply_error(self, technical_message):
        print(f"[error talking to the AI] {technical_message}")
        self.enter_state("TALKING", text="Deu erro ao pensar - o Ollama tá rodando? (veja o console)")

    def _on_transcription(self, text):
        text = (text or "").strip()
        if not text:
            self.enter_state("TALKING", text="Não te ouvi direito, tenta de novo?")
            return
        self.process_question(text)

    def _on_greeting_finished(self):
        if self.current_state == "GREETING":
            self.enter_state("IDLE")

    def _on_speech_finished(self):
        if self.current_state == "TALKING":
            self.enter_state("IDLE")

    # ------------------------------------------------------------------
    # Proactive Todoist reminders
    # ------------------------------------------------------------------
    def _check_todoist_reminders(self):
        self._reminder_worker = TodoistCheckWorker(self.todoist)
        self._reminder_worker.result.connect(self._on_todoist_check_result)
        self._reminder_worker.error.connect(lambda e: print(f"[todoist reminder check failed] {e}"))
        self._reminder_worker.start()

    def _on_todoist_check_result(self, tasks):
        if self.current_state != "IDLE":
            return  # try again on the next poll instead of interrupting
        new_tasks = [t for t in tasks if t["id"] not in self._reminded_task_ids]
        if not new_tasks:
            return
        for task in new_tasks:
            self._reminded_task_ids.add(task["id"])

        if len(new_tasks) == 1:
            text = f"Lembrete: você tem a tarefa \"{new_tasks[0]['content']}\" pra fazer."
        else:
            items = ", ".join(task["content"] for task in new_tasks[:5])
            text = f"Lembrete: você tem {len(new_tasks)} tarefas pendentes: {items}."
        self.enter_state("TALKING", text=text)

    # ------------------------------------------------------------------
    # Proactive Google Calendar reminders
    # ------------------------------------------------------------------
    def _check_calendar_reminders(self):
        self._calendar_worker = CalendarCheckWorker(self.calendar)
        self._calendar_worker.result.connect(self._on_calendar_check_result)
        self._calendar_worker.error.connect(lambda e: print(f"[calendar reminder check failed] {e}"))
        self._calendar_worker.start()

    def _on_calendar_check_result(self, events):
        if self.current_state != "IDLE":
            return  # try again on the next poll instead of interrupting

        soon_cutoff = datetime.datetime.now().astimezone() + datetime.timedelta(minutes=CALENDAR_LOOKAHEAD_MINUTES)
        upcoming_soon = []
        for event in events:
            if event["id"] in self._reminded_event_ids or not event.get("start"):
                continue
            try:
                start = datetime.datetime.fromisoformat(event["start"])
            except ValueError:
                continue
            if start.tzinfo is None:
                start = start.astimezone()
            if start <= soon_cutoff:
                upcoming_soon.append(event)

        if not upcoming_soon:
            return
        for event in upcoming_soon:
            self._reminded_event_ids.add(event["id"])

        if len(upcoming_soon) == 1:
            text = f"Lembrete: você tem \"{upcoming_soon[0]['summary']}\" daqui a pouco."
        else:
            items = ", ".join(event["summary"] for event in upcoming_soon[:5])
            text = f"Lembrete: você tem {len(upcoming_soon)} eventos chegando: {items}."
        self.enter_state("TALKING", text=text)

    # ------------------------------------------------------------------
    # Proactive language learning tips (German)
    # ------------------------------------------------------------------
    def _schedule_next_language_tip(self):
        interval_ms = random.randint(LANGUAGE_TIP_MIN_INTERVAL_MS, LANGUAGE_TIP_MAX_INTERVAL_MS)
        QTimer.singleShot(interval_ms, self._language_tip_tick)

    def _language_tip_tick(self):
        if self.current_state != "IDLE":
            QTimer.singleShot(LANGUAGE_TIP_RETRY_INTERVAL_MS, self._language_tip_tick)
            return
        tip = random.choice(language_learning.GERMAN_TIPS)
        self.enter_state("TALKING", text=tip)
        self._schedule_next_language_tip()

    # ------------------------------------------------------------------
    # Claude Code notifications (see notify_claude_hook.py)
    # ------------------------------------------------------------------
    def _notify_queue_size(self):
        try:
            return os.path.getsize(NOTIFY_QUEUE_FILE)
        except OSError:
            return 0

    def _check_claude_notifications(self):
        if self.current_state != "IDLE":
            return  # try again on the next poll instead of interrupting
        size = self._notify_queue_size()
        if size <= self._notify_queue_offset:
            self._notify_queue_offset = size  # file was truncated/rotated
            return

        with open(NOTIFY_QUEUE_FILE, "r", encoding="utf-8") as f:
            f.seek(self._notify_queue_offset)
            new_lines = f.readlines()
        self._notify_queue_offset = size

        # Multiple events can pile up between polls (e.g. several quick
        # Stop hooks) - only the most recent one still worth announcing
        # gets spoken, the rest are just marked as read.
        now = time.time()
        latest_entry = None
        for line in new_lines:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if now - entry.get("ts", 0) <= NOTIFY_MAX_AGE_SECONDS:
                latest_entry = entry

        if latest_entry is None:
            return
        project = os.path.basename((latest_entry.get("cwd") or "").rstrip("/")) or "?"
        text = f"Claude ({project}): {latest_entry['message']}"
        self.enter_state("TALKING", text=text)

    # ------------------------------------------------------------------
    # Speech bubble (widgets inside the monkey's own window)
    # ------------------------------------------------------------------
    def _height_needed_for_text(self, text, width):
        padding_margin = 20  # ~ stylesheet padding (8px each side) + slack
        fm = QFontMetrics(self.bubble_label.font())
        rect = fm.boundingRect(0, 0, width - padding_margin, 0, Qt.TextWordWrap, text)
        return rect.height() + padding_margin

    def _adjust_bubble_height(self, new_bubble_height):
        """Resizes the bubble area (and the whole window) while keeping the
        monkey anchored in the same screen spot - the window grows UPWARD."""
        delta = new_bubble_height - self._current_bubble_height
        if delta == 0:
            return
        sprite_width, sprite_height = self.canvas_size
        sprite_x = (self._window_width - sprite_width) // 2

        self.setGeometry(self.x(), self.y() - delta, self._window_width, sprite_height + new_bubble_height)
        self.label.setGeometry(sprite_x, new_bubble_height, sprite_width, sprite_height)
        self.bubble_label.setGeometry(0, 0, self._window_width, new_bubble_height - 12)
        self.bubble_input.setGeometry(0, 0, self._window_width, new_bubble_height - 12)
        self._current_bubble_height = new_bubble_height

    def _show_bubble_text(self, text):
        self.bubble_input.hide()
        needed_height = self._height_needed_for_text(text, self._window_width)
        bubble_height = max(BUBBLE_HEIGHT, min(needed_height + 12, BUBBLE_HEIGHT_MAX))
        self._adjust_bubble_height(bubble_height)
        self.bubble_label.setText(text)
        self.bubble_label.show()

    def _hide_bubble(self):
        self.bubble_label.hide()
        self.bubble_input.hide()
        self._adjust_bubble_height(BUBBLE_HEIGHT)

    def _toggle_bubble_input(self):
        if self.bubble_input.isVisible():
            self._hide_bubble()
        else:
            self.bubble_label.hide()
            self._adjust_bubble_height(BUBBLE_HEIGHT)
            self.bubble_input.show()
            self.bubble_input.setFocus()

    def _send_from_input(self):
        text = self.bubble_input.text().strip()
        self.bubble_input.clear()
        self.bubble_input.hide()
        if text:
            self.process_question(text)

    # ------------------------------------------------------------------
    # Loading and pre-processing
    # ------------------------------------------------------------------
    def load_definitions(self):
        if not os.path.exists(ANIMATIONS_FILE):
            print(f"Warning: {ANIMATIONS_FILE} not found.")
            return {}
        with open(ANIMATIONS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)

    def get_file_pixmap(self, file_name):
        if file_name in self.file_pixmap_cache:
            return self.file_pixmap_cache[file_name]
        path = os.path.join(IMAGES_FOLDER, file_name)
        if not os.path.exists(path):
            print(f"Error: file not found {path}")
            return None
        pm = remove_background(path)
        self.file_pixmap_cache[file_name] = pm
        return pm

    def compose_step(self, step):
        """Converts a JSON step ('alone' or 'combined') into a single,
        ready-to-display QPixmap, supporting up to 3 layers."""
        if step["mode"] == "alone":
            return self.get_file_pixmap(step["file"])

        base_pm = self.get_file_pixmap(step["file"])
        if base_pm is None:
            return None
        composed = QPixmap(base_pm.size())
        composed.fill(Qt.transparent)
        painter = QPainter(composed)
        painter.drawPixmap(0, 0, base_pm)

        # Layer 2 (e.g. mailbox)
        overlay_pm = self.get_file_pixmap(step.get("extra_file"))
        if overlay_pm is not None:
            painter.drawPixmap(step.get("offset_x", 0), step.get("offset_y", 0), overlay_pm)

        # Layer 3 (e.g. eyes/glance cutout)
        if "extra_file2" in step:
            overlay_pm2 = self.get_file_pixmap(step.get("extra_file2"))
            if overlay_pm2 is not None:
                painter.drawPixmap(step.get("offset_x2", 0), step.get("offset_y2", 0), overlay_pm2)

        painter.end()
        return composed

    def prepare_all_frames(self):
        for name, data in self.animation_definitions.items():
            description = data.get("description", "")
            if description:
                print(f"[animation '{name}'] {description}")

            frames = []
            for step in data.get("steps", []):
                pm = self.compose_step(step)
                if pm is not None:
                    frames.append(pm)
            self.ready_frames[name] = frames

    def calculate_canvas_size(self):
        max_width, max_height = 100, 100
        for frames in self.ready_frames.values():
            for pm in frames:
                max_width = max(max_width, pm.width())
                max_height = max(max_height, pm.height())
        return max_width, max_height

    # ------------------------------------------------------------------
    # Playback (with smooth transitions between frames/animations)
    # ------------------------------------------------------------------
    def _pixmap_on_canvas(self, sprite_pixmap):
        canvas = QPixmap(*self.canvas_size)
        canvas.fill(Qt.transparent)
        painter = QPainter(canvas)
        x = (self.canvas_size[0] - sprite_pixmap.width()) // 2
        y = self.canvas_size[1] - sprite_pixmap.height()
        painter.drawPixmap(x, max(y, 0), sprite_pixmap)
        painter.end()
        return canvas

    def _blend_pixmaps(self, pm_from, pm_to, fraction_to):
        """Combines two frames (already at canvas size) by opacity, to
        create a smooth transition instead of a hard cut between poses."""
        if pm_from is None:
            return pm_to
        result = QPixmap(pm_to.size())
        result.fill(Qt.transparent)
        painter = QPainter(result)
        painter.drawPixmap(0, 0, pm_from)
        painter.setOpacity(max(0.0, min(1.0, fraction_to)))
        painter.drawPixmap(0, 0, pm_to)
        painter.end()
        return result

    def play_animation(self, name, next_after_finish=None, once=False, on_finish_callback=None):
        """Switches the animation being shown, always with a short
        transition from whatever was on screen (avoids a hard "jump"
        between poses). With once=True, plays only a single pass (ignoring
        the JSON's loop flag) and moves on to next_after_finish - used for
        one-shot gestures (blink, yawn) that shouldn't keep repeating
        forever. on_finish_callback is an optional callback fired when this
        pass actually finishes (handy to only schedule the next gesture
        after the current one truly ended, instead of on a fixed interval
        that could interrupt it midway)."""
        if name not in self.ready_frames or not self.ready_frames[name]:
            print(f"Animation '{name}' doesn't exist (or is empty) in {ANIMATIONS_FILE}.")
            return

        target = self._pixmap_on_canvas(self.ready_frames[name][0])

        self.current_animation = name
        self.frame_index = 0
        self.next_animation_after_finish = next_after_finish
        self.force_once = once
        self._on_finish_callback = on_finish_callback

        if self._pm_next is not None:
            self._pm_previous = self._pm_next
            self._segment_duration = SWITCH_TRANSITION_DURATION
        else:
            self._pm_previous = target
            self._segment_duration = 0.0
        self._pm_next = target
        self._segment_start = time.monotonic()

    def current_animation_description(self):
        """Returns the description text of the animation currently playing
        (handy if you want to show/log what the buddy is doing right now)."""
        if not self.current_animation:
            return ""
        return self.animation_definitions.get(self.current_animation, {}).get("description", "")

    def _render_tick(self):
        """Runs at ~30fps, independent of each animation's fps: interpolates
        between the previous and next frame to smooth out the motion."""
        if self._pm_next is None:
            return
        now = time.monotonic()
        fraction = 1.0 if self._segment_duration <= 0 else (now - self._segment_start) / self._segment_duration

        if fraction >= 1.0:
            self.label.setPixmap(self._pm_next)
            self._advance_frame()
        else:
            self.label.setPixmap(self._blend_pixmaps(self._pm_previous, self._pm_next, fraction))

    def _advance_frame(self):
        data = self.animation_definitions[self.current_animation]
        frames = self.ready_frames[self.current_animation]
        total_frames = len(frames)
        fps = data.get("fps", 8)
        next_index = self.frame_index + 1

        if next_index >= total_frames:
            if data.get("loop", True) and not self.force_once:
                next_index = 0
            else:
                next_animation = self.next_animation_after_finish
                callback = self._on_finish_callback
                self._on_finish_callback = None
                if next_animation and next_animation in self.ready_frames:
                    self.play_animation(next_animation)
                if callback:
                    callback()
                return

        self.frame_index = next_index
        self._pm_previous = self._pm_next
        self._pm_next = self._pixmap_on_canvas(frames[self.frame_index])
        self._segment_duration = 1.0 / fps
        self._segment_start = time.monotonic()

    # ------------------------------------------------------------------
    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.drag_position = event.globalPos() - self.frameGeometry().topLeft()
            self._dragged = False
            event.accept()

    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.LeftButton:
            self._dragged = True
            self.move(event.globalPos() - self.drag_position)
            event.accept()

    def mouseReleaseEvent(self, event):
        if event.button() == Qt.LeftButton and not self._dragged:
            self._toggle_bubble_input()
        event.accept()

    def mouseDoubleClickEvent(self, event):
        """Double-click makes the monkey wave hello on demand."""
        self.enter_state("GREETING")

    def contextMenuEvent(self, event):
        menu = QMenu(self)
        mute_action = menu.addAction("Mute voice")
        mute_action.setCheckable(True)
        mute_action.setChecked(self.voice.muted)
        menu.addAction("Push-to-talk: hold F9 to talk").setEnabled(False)
        menu.addSeparator()
        quit_action = menu.addAction("Quit")

        chosen = menu.exec_(event.globalPos())
        if chosen == mute_action:
            self.voice.muted = not self.voice.muted
        elif chosen == quit_action:
            QApplication.instance().quit()


if __name__ == "__main__":
    app = QApplication(sys.argv)

    # 1. Set up Ctrl+C handling HERE (before running the app)
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    buddy = AnimatedBuddy()
    buddy.show()
    app.aboutToQuit.connect(buddy.voice.stop)

    # 2. Start the GUI loop
    sys.exit(app.exec_())
