"""
Language learning tips - German
===================================
Short, curated tips (vocabulary or grammar rules) the monkey speaks out
loud from time to time while idle (see animation.py's
_schedule_next_language_tip / _language_tip_tick). Kept as a fixed list
instead of generating them via Ollama - instant (no "thinking" wait) and
avoids a small model hallucinating a wrong translation.

Written in Portuguese (the monkey's persona language, see brain.py's
SYSTEM_PROMPT and voice.py's TTS_VOICE) explaining a German word or rule,
kept short since it's read out loud in the speech bubble.

227 of these were extracted from "Hammer's German Grammar and
Usage" (7th edition, Martin Durrell) - specifically the
chapters on nouns, case, personal pronouns, articles, adjectives,
numerals, verb conjugation, tenses, modal auxiliaries and word order,
picked as the most fundamental/beginner-relevant of the book's 21
chapters. Compressed down to one short spoken sentence each; anything
too exception-heavy to compress accurately was left out rather than
risk teaching something wrong. Another 60 come from Preply's "Palavras
mais usadas em alemão" article (https://preply.com/pt/blog/palavras-mais-usadas-em-alemao/),
covering the 100 most common German words by part of speech.
"""

GERMAN_TIPS = [
    # --- Basics (vocabulary, greetings, numbers 1-10) ---
    "Em alemão, 'Hund' significa cachorro.",
    "Em alemão, 'Katze' significa gato.",
    "Em alemão, 'Wasser' significa água.",
    "Em alemão, 'Brot' significa pão.",
    "Em alemão, 'Haus' significa casa.",
    "Em alemão, 'Danke' significa obrigado.",
    "Em alemão, 'Bitte' significa por favor, e também de nada.",
    "Em alemão, 'Guten Morgen' significa bom dia.",
    "Em alemão, 'Guten Abend' significa boa noite, pra quando você chega.",
    "Em alemão, 'Tschüss' é um jeito informal de dizer tchau.",
    "Em alemão, 'Freund' significa amigo, mas 'Freundin' é a versão feminina.",
    "Em alemão, 'Arbeit' significa trabalho.",
    "Em alemão, 'Zeit' significa tempo.",
    "Em alemão, 'schnell' significa rápido.",
    "Em alemão, 'langsam' significa devagar.",
    "Em alemão, 'heute' significa hoje, 'morgen' significa amanhã.",
    "Regra rápida: em alemão, todo substantivo é escrito com a primeira letra maiúscula, sempre.",
    "Regra rápida: em frases afirmativas simples, o verbo conjugado vem sempre na segunda posição.",
    "Regra rápida: em alemão, o plural não segue uma regra única - cada substantivo tem seu próprio jeito de virar plural.",
    "Regra rápida: 'ich' é eu, 'du' é você, 'er/sie/es' é ele/ela/isso.",
    "Regra rápida: 'nicht' é a palavra pra negar uma frase, geralmente vem perto do fim.",
    "Regra rápida: os números 21 a 99 em alemão se falam invertidos, tipo 'einundzwanzig' é 'um e vinte', ou seja, vinte e um.",
    "Falso amigo: 'also' em alemão não é 'também' - significa 'então' ou 'ou seja'.",
    "Falso amigo: 'Chef' em alemão não é cozinheiro - significa chefe, patrão.",
    "Falso amigo: 'Gift' em alemão não é presente - significa veneno.",
    "Em alemão, os dias da semana: Montag é segunda, Dienstag é terça, Mittwoch é quarta.",
    "Em alemão, os dias da semana: Donnerstag é quinta, Freitag é sexta, e Samstag ou Sonnabend é sábado.",
    "Em alemão, 'eins, zwei, drei' são um, dois, três.",
    "Em alemão, 'vier, fünf, sechs' são quatro, cinco, seis.",
    "Em alemão, 'sieben, acht, neun, zehn' são sete, oito, nove, dez.",
    "Em alemão, 'Ich liebe dich' significa eu te amo.",
    "Em alemão, 'Wie geht's?' significa como você está?",
    "Em alemão, 'Ich verstehe nicht' significa eu não entendo.",
    "Em alemão, 'Entschuldigung' significa desculpa, ou dá pra usar pra chamar atenção tipo 'com licença'.",

    # --- Nouns (Hammer's German Grammar and Usage, 7th ed.) ---
    "Em alemão, todo substantivo tem um gênero fixo - masculino, feminino ou neutro - que não tem relação direta com o sentido da palavra.",
    "Regra rápida: substantivos terminados em -chen ou -lein são sempre neutros, como 'das Mädchen' (a menina).",
    "Regra rápida: substantivos terminados em -heit, -keit ou -ung são sempre femininos, como 'die Zeitung' (o jornal).",
    "Regra rápida: substantivos terminados em -ismus, -or ou -us costumam ser masculinos, como 'der Motor' (o motor).",
    "Regra rápida: substantivos com o prefixo Ge- costumam ser neutros, como 'das Gespräch' (a conversa).",
    "Regra rápida: os nomes das estações do ano, meses e dias da semana em alemão são quase sempre masculinos, como 'der Sommer' (o verão).",
    "Regra rápida: metais e elementos químicos em alemão costumam ser neutros, como 'das Gold' (o ouro) e 'das Eisen' (o ferro).",
    "Regra rápida: bebidas alcoólicas e à base de plantas costumam ser masculinas em alemão, como 'der Kaffee' e 'der Wein' - exceto 'das Bier' (a cerveja).",
    "Regra rápida: rios fora dos países de língua alemã costumam ser masculinos, como 'der Nil', mas os rios dentro da Alemanha costumam ser femininos, como 'die Elbe'.",
    "Regra rápida: no plural, todo substantivo alemão usa o mesmo artigo definido, 'die', não importa qual era o gênero no singular.",
    "Em alemão, 'Tisch' significa mesa, e é uma palavra masculina: 'der Tisch'.",
    "Em alemão, 'Wand' significa parede, e é uma palavra feminina: 'die Wand'.",
    "Em alemão, 'Fenster' significa janela, e é uma palavra neutra: 'das Fenster'.",
    "Regra rápida: quando um substantivo alemão é formado pela junção de duas palavras, o gênero é sempre o gênero da última palavra.",
    "Regra rápida: muitos substantivos masculinos formam o plural com -e, às vezes com trema na vogal, como 'der Hund' vira 'die Hunde'.",
    "Regra rápida: a maioria dos substantivos femininos forma o plural com -en ou -n, como 'die Frau' vira 'die Frauen'.",
    "Regra rápida: substantivos terminados em -el, -en ou -er geralmente não mudam no plural, como 'der Lehrer' continua 'die Lehrer'.",
    "Regra rápida: muitos substantivos neutros de uma sílaba formam o plural com -er e trema, como 'das Buch' vira 'die Bücher'.",
    "Regra rápida: palavras emprestadas do inglês ou francês costumam formar o plural com -s em alemão, como 'das Hotel' vira 'die Hotels'.",
    "Em alemão existe um grupo de substantivos masculinos chamados 'fracos', que ganham a terminação -n ou -en em quase todos os casos, como 'der Student' vira 'den Studenten'.",
    "Regra rápida: substantivos masculinos e neutros ganham a terminação -s ou -es no caso genitivo singular, como 'das Buch' vira 'des Buches'.",
    "Em alemão, 'Junge' significa menino, e apesar de terminar em -e (que normalmente indica palavra feminina), é uma palavra masculina.",
    "Regra rápida: substantivos formados a partir de infinitivos de verbos são sempre neutros em alemão, como 'das Essen' (a comida, o ato de comer).",

    # --- Case (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: alemão tem quatro casos gramaticais - nominativo, acusativo, genitivo e dativo - que mostram a função de cada palavra na frase.",
    "Regra rápida: o caso nominativo marca o sujeito da frase, ou seja, quem pratica a ação do verbo.",
    "Regra rápida: o caso acusativo marca o objeto direto do verbo, a pessoa ou coisa que sofre a ação diretamente.",
    "Regra rápida: o caso dativo marca o objeto indireto do verbo, geralmente quem recebe alguma coisa.",
    "Regra rápida: o caso genitivo indica posse, como em 'das Haus meines Bruders' (a casa do meu irmão).",
    "Regra rápida: em alemão, ao contrário do português, não é a ordem das palavras que define quem é sujeito ou objeto, e sim as terminações das palavras.",
    "Regra rápida: em alemão, o sujeito não precisa vir antes do verbo, porque a terminação da palavra já mostra quem é o sujeito.",
    "Regra rápida: depois de verbos como 'sein' (ser), a palavra que descreve o sujeito também fica no caso nominativo.",
    "Regra rápida: o caso acusativo é usado para expressar duração de tempo sem preposição, como em 'einen Monat' (durante um mês).",
    "Regra rápida: em cumprimentos como 'Guten Morgen' e 'Gute Nacht', a palavra usada está no caso acusativo.",
    "Em alemão, o caso genitivo é mais comum na escrita formal; na fala do dia a dia, costuma-se usar a preposição 'von' no lugar dele.",
    "Regra rápida: com nomes próprios, o genitivo em alemão funciona como o 's do inglês e vem antes do nome, como 'Annas Buch' (o livro da Ana).",
    "Regra rápida: o dativo é o caso mais usado depois de preposições em alemão.",
    "Regra rápida: o caso dativo também indica posse em alemão, especialmente com partes do corpo e roupas, como em 'Sie zogen dem Verletzten das Hemd aus' (tiraram a camisa do ferido).",
    "Regra rápida: alguns verbos alemães, como 'helfen' (ajudar) e 'danken' (agradecer), pedem sempre o caso dativo, nunca o acusativo.",
    "Em alemão, 'Ich gebe dem Hamster sein Futter' significa 'eu dou comida ao hamster' - 'dem Hamster' está no dativo porque é quem recebe.",
    "Regra rápida: para dizer 'estou com frio' em alemão nunca se diz 'Ich bin kalt' - o certo é 'Mir ist kalt', usando o caso dativo.",
    "Regra rápida: depois da preposição 'trotz' (apesar de), o alemão formal usa o caso genitivo, como em 'trotz des Regens' (apesar da chuva).",
    "Em alemão, 'Ich kaufe einen neuen Fernseher' significa 'eu compro uma televisão nova' - 'einen neuen Fernseher' está no acusativo por ser o objeto direto.",
    "Regra rápida: o caso dativo também pode indicar a pessoa em benefício de quem uma ação é feita, como em 'Ich habe ihr die Tür geöffnet' (eu abri a porta para ela).",
    "Regra rápida: para expressar distância percorrida, o alemão usa o caso acusativo sem preposição, como em 'die Straße heruntergehen' (descer a rua).",
    "Regra rápida: alguns adjetivos em alemão pedem o caso dativo, como em 'Er ist seinem Bruder sehr ähnlich' (ele é muito parecido com o irmão dele).",

    # --- Personal pronouns (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: os pronomes pessoais em alemão são ich, du, er, sie, es, wir, ihr e sie/Sie.",
    "Em alemão, 'ich' significa eu, e 'du' significa você, no sentido informal.",
    "Regra rápida: use 'du' com crianças, família, amigos próximos e animais.",
    "Regra rápida: use 'Sie', com S maiúsculo, para falar com adultos desconhecidos de forma formal.",
    "Regra rápida: 'ihr' é o plural informal de 'du', usado para falar com um grupo.",
    "Regra rápida: entre adultos, 'du' e 'Sie' são sempre recíprocos - nunca uma pessoa usa um e a outra usa o outro.",
    "Regra rápida: usar 'du' com um adulto desconhecido é considerado rude em alemão.",
    "Em alemão, 'sich' é o pronome reflexivo usado com ele, ela, eles e com 'Sie'.",
    "Em alemão, 'mich' significa 'me' e 'dich' significa 'te', usados em verbos reflexivos como 'sich waschen', lavar-se.",
    "Regra rápida: verbos reflexivos são muito mais comuns em alemão do que em português.",
    "Regra rápida: em alemão, os pronomes er, sie e es concordam com o gênero gramatical da palavra, não com o sexo natural da coisa.",
    "Regra rápida: para coisas, use um advérbio como 'damit' (com isso) em vez de preposição com pronome.",
    "Regra rápida: para pessoas, use preposição mais pronome, como em 'ich spiele mit ihr', eu brinco com ela.",
    "Em alemão, 'es' é o sujeito impessoal de verbos como 'es regnet', está chovendo.",
    "Regra rápida: 'es gibt' significa 'há' ou 'existe' em alemão.",
    "Regra rápida: para dizer 'sou eu' em alemão, diz-se 'ich bin es', literalmente 'eu sou isso'.",
    "Em alemão, 'selbst' ou 'selber' dão ênfase a um pronome, como em 'eu mesmo'.",
    "Em alemão, 'einander' significa 'um ao outro', como em 'sie lieben einander', eles se amam.",
    "Regra rápida: as formas genitivas dos pronomes, como 'meiner' e 'deiner', são raras e soam formais.",
    "Regra rápida: no alemão falado, os pronomes 'ich', 'du' e 'es' às vezes somem no início da frase.",
    "Em alemão, 'Sie' maiúsculo é a forma formal de você; 'sie' minúsculo pode significar ela ou eles.",
    "Regra rápida: em cartas informais, os alemães às vezes escrevem 'Du' e 'Dein' com maiúscula por carinho.",
    "Em alemão, títulos como 'der Herr' às vezes substituem 'Sie' em lojas e restaurantes.",

    # --- Articles (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: alemão tem três artigos definidos - der, die e das - e o plural sempre usa die.",
    "Regra rápida: o artigo indefinido é 'ein' para masculino e neutro, e 'eine' para feminino.",
    "Regra rápida: o artigo definido muda com o caso - no acusativo masculino, 'der' vira 'den'.",
    "Em alemão, o artigo definido masculino no dativo é 'dem', e no genitivo é 'des'.",
    "Regra rápida: o artigo indefinido 'ein' não tem plural - no plural, o substantivo fica sem artigo.",
    "Em alemão, a negação de 'ein' é 'kein', que significa 'nenhum', e diferente de 'ein', 'kein' tem plural.",
    "Regra rápida: contrações comuns juntam preposição e artigo, como 'im' (in + dem) e 'am' (an + dem).",
    "Em alemão, substantivos abstratos costumam levar artigo definido, como em 'die Zeit vergeht', o tempo passa.",
    "Em alemão, 'die Musik' e 'die Geschichte' levam artigo definido para falar de música e história em geral.",
    "Regra rápida: nomes de países femininos ou no plural sempre levam artigo, como 'die Schweiz', a Suíça.",
    "Regra rápida: a maioria dos nomes de países e cidades neutros não leva artigo, como 'Deutschland' e 'Spanien'.",
    "Regra rápida: em alemão, partes do corpo e roupas costumam usar artigo definido em vez de possessivo.",
    "Regra rápida: profissões não levam artigo depois do verbo 'sein', como em 'Er ist Arzt', ele é médico.",
    "Em alemão, meses e estações levam artigo definido, como 'der April' e 'im Winter', no inverno.",
    "Regra rápida: as grandes festas não levam artigo, como 'Weihnachten', Natal, e 'Ostern', Páscoa.",
    "Em alemão, nomes de ruas levam artigo definido, como em 'die Goethestraße', a rua Goethe.",
    "Regra rápida: em alemão padrão, nomes de pessoas normalmente não levam artigo.",
    "Em alemão, o artigo definido também tem sentido distributivo, como em 'zweimal die Woche', duas vezes por semana.",
    "Regra rápida: o genitivo de um substantivo quase sempre precisa de um artigo para ficar claro.",
    "Em alemão, o artigo definido é levemente pronunciado na fala, por isso costuma ser reduzido.",
    "Regra rápida: nomes de doenças levam artigo quando são conhecidas em geral, mas nenhum artigo depois de 'haben'.",
    "Em alemão, nomes de refeições como 'das Frühstück' levam artigo quando são conhecidas, mas podem ficar sem artigo em sentido indefinido.",

    # --- Adjectives (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: em alemão, o adjetivo antes do substantivo sempre leva uma terminação, mas depois do verbo 'sein' ele fica sem terminação nenhuma.",
    "Em alemão, 'der Mann ist klug' não leva terminação no adjetivo, mas 'ein kluger Mann' leva - a diferença é estar antes ou depois do substantivo.",
    "Regra rápida: quando não há artigo antes do substantivo, o adjetivo alemão leva a terminação forte, como em 'gutes Brot', pão bom.",
    "Regra rápida: depois de 'der', 'die' ou 'das', o adjetivo alemão quase sempre termina em -e ou -en, nunca em -er ou -es.",
    "Em alemão, no nominativo singular depois do artigo definido, o adjetivo sempre termina em -e: 'der gute Wein', 'die gute Suppe', 'das gute Brot'.",
    "Regra rápida: depois de 'ein', 'kein' ou de um possessivo como 'mein' sem terminação, o adjetivo alemão leva terminação forte, como em 'ein guter Wein'.",
    "Em alemão, no feminino singular o adjetivo quase sempre termina em -e, seja no nominativo ou no acusativo: 'eine gute Suppe'.",
    "Regra rápida: sem nenhum artigo antes, o substantivo masculino no nominativo pede adjetivo terminado em -er, como em 'guter Wein', vinho bom.",
    "Regra rápida: quando dois adjetivos descrevem o mesmo substantivo em alemão, os dois recebem a mesma terminação, como em 'gutes bayrisches Bier'.",
    "Regra rápida: depois de palavras como 'viel', 'wenig' ou 'ein paar', o adjetivo alemão costuma levar terminação forte, como em 'viel indischer Tee'.",
    "Regra rápida: em alemão, qualquer adjetivo pode virar substantivo - basta escrever com letra maiúscula, como 'der Alte', o velho.",
    "Em alemão, 'der Deutsche' significa 'o alemão' e se declina como um adjetivo, não como um substantivo comum.",
    "Regra rápida: em alemão, o comparativo sempre se forma com -er e o superlativo com -st, não importa o tamanho da palavra - não existe um 'mais' separado como em português.",
    "Em alemão, 'gut' (bom) tem comparação irregular: gut, besser, am besten - parecido com 'bom, melhor, ótimo' em português.",
    "Em alemão, 'groß' (grande) no comparativo é 'größer' e no superlativo 'am größten' - repare no Umlaut na vogal.",
    "Regra rápida: vários adjetivos alemães ganham Umlaut no comparativo, como 'alt' vira 'älter' e 'jung' vira 'jünger'.",
    "Em alemão, 'als' significa 'do que' nas comparações: 'Peter ist älter als Thomas' - Peter é mais velho do que Thomas.",
    "Regra rápida: para dizer 'tão... quanto' em alemão, usa-se 'so... wie', como em 'so alt wie', tão velho quanto.",
    "Em alemão, repetir 'immer' antes do comparativo indica algo crescente: 'immer teurer' significa 'cada vez mais caro'.",
    "Regra rápida: 'quanto mais... mais' em alemão se diz com 'je... desto', como em 'je älter, desto klüger' - quanto mais velho, mais sábio.",
    "Regra rápida: o adjetivo 'hoch' (alto) muda para 'hoh-' quando ganha terminação: 'der Berg ist hoch', mas 'ein hoher Berg', uma montanha alta.",
    "Em alemão, algumas cores como 'rosa' e 'lila' nunca mudam de terminação, seja qual for o gênero do substantivo.",

    # --- Numerals (Hammer's German Grammar and Usage, 7th ed.) ---
    "Em alemão, os números de 13 a 19 seguem o padrão 'número + zehn': dreizehn (13), vierzehn (14), fünfzehn (15).",
    "Regra rápida: em alemão, os números compostos são ditos ao contrário do português - 21 é 'einundzwanzig', literalmente 'um e vinte'.",
    "Em alemão, as dezenas seguem um padrão só: zwanzig (20), dreißig (30), vierzig (40), fünfzig (50), sechzig (60), siebzig (70), achtzig (80), neunzig (90).",
    "Em alemão, 'hundert' significa cem e 'tausend' significa mil, normalmente sem precisar do 'ein' na frente, como em 'hundert Euro'.",
    "Regra rápida: em números compostos alemães como 'hunderteins' (cento e um), o 'und' entre 'hundert' e a unidade é opcional.",
    "Em alemão, 'eine Million' e 'eine Milliarde' são substantivos femininos e têm plural: 'zwei Millionen', dois milhões.",
    "Cuidado: a 'Milliarde' alemã é o bilhão em português, mil milhões, e a 'Billion' alemã é o trilhão - não confie na semelhança com o inglês.",
    "Em alemão coloquial, 'zwo' é usado no lugar de 'zwei' ao telefone, para não confundir com 'drei'.",
    "Regra rápida: em alemão, anos entre 1100 e 1999 são ditos em centenas, como 'neunzehnhundertsechsundneunzig' para 1996.",
    "Em alemão, anos a partir de 2000 usam 'zweitausend' na frente, como 'zweitausendneun' para 2009 - diferente do inglês, que usa 'twenty'.",
    "Regra rápida: em alemão, os números ordinais de 2 a 19 terminam em -te, como 'der zweite', o segundo, e 'der zehnte', o décimo.",
    "Regra rápida: em alemão, os números ordinais a partir de 20 terminam em -ste, como 'der zwanzigste', o vigésimo.",
    "Em alemão, 'primeiro' é 'erste', 'terceiro' é 'dritte' e 'sétimo' é 'siebte' - exceções ao padrão normal dos números ordinais.",
    "Regra rápida: em alemão, os números ordinais escritos usam um ponto depois do número, como '14. Mai', 14 de maio.",
    "Em alemão, os números ordinais se declinam como adjetivos comuns, com as mesmas terminações -e e -en.",
    "Em alemão, 'primeiramente', 'em segundo lugar' e 'em terceiro lugar' se dizem 'erstens', 'zweitens' e 'drittens'.",
    "Em alemão, frações são substantivos neutros formados com o sufixo -tel: 'ein Drittel' é um terço, 'ein Viertel' é um quarto.",
    "Regra rápida: em alemão, os números decimais usam vírgula, não ponto - '4,75' se lê 'vierkommasiebenfünf'.",
    "Regra rápida: em alemão, 'halb vier' significa três e meia, não quatro e meia - a expressão aponta para a próxima hora cheia.",
    "Em alemão falado, 'Viertel nach drei' é três e quinze, e 'Viertel vor vier' é três e quarenta e cinco.",
    "Regra rápida: no alemão oficial, como em horários e na TV, usa-se sempre o relógio de 24 horas, com a palavra 'Uhr' dita junto ao número, como 'zwanzig Uhr'.",
    "Em alemão, para dizer a data usa-se o número ordinal: 'der fünfte April' significa 'o quinto de abril', ou seja, dia 5 de abril.",
    "Regra rápida: em datas alemãs escritas com números, o dia vem antes do mês, como em '5.6.2019' para 5 de junho de 2019 - igual ao português.",
    "Em alemão, 'je' antes de um número significa 'cada': 'Ich gab den Jungen je zehn Euro' - dei dez euros para cada menino.",
    "Regra rápida: para multiplicar em alemão, usa-se 'mal': 'sieben mal vier ist achtundzwanzig', sete vezes quatro é vinte e oito.",

    # --- Verbs: conjugation (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: o infinitivo dos verbos alemães termina em -en ou -n, como kaufen (comprar) e wandern (caminhar).",
    "Regra rápida: no presente do indicativo, as terminações regulares são -e, -st, -t, -en, -t, -en para ich, du, er, wir, ihr, sie.",
    "Em alemão, verbos fracos formam o passado simples com a terminação -te, como kaufen vira kaufte.",
    "Em alemão, verbos fortes formam o passado simples mudando a vogal da raiz, como singen vira sang.",
    "Regra rápida: o particípio passado dos verbos fracos é formado com ge- no início e -t no final, como gekauft.",
    "Regra rápida: o particípio passado dos verbos fortes é formado com ge- no início e -en no final, como gesungen.",
    "Em alemão, 'sein' significa ser ou estar, e se conjuga assim: ich bin, du bist, er ist.",
    "Em alemão, 'haben' significa ter, e se conjuga assim: ich habe, du hast, er hat.",
    "Em alemão, 'werden' significa tornar-se ou ficar, e se conjuga assim: ich werde, du wirst, er wird.",
    "Regra rápida: os verbos modais como können e müssen não recebem terminação na terceira pessoa do singular, por isso se diz er kann, não er kannt.",
    "Regra rápida: o tempo perfeito em alemão se forma com haben ou sein mais o particípio passado no fim da frase.",
    "Regra rápida: a maioria dos verbos alemães usa haben no perfeito, mas verbos de movimento como gehen e fahren costumam usar sein.",
    "Em alemão, os verbos sein e bleiben sempre formam o tempo perfeito com sein, nunca com haben.",
    "Regra rápida: em verbos separáveis como ankommen, o prefixo vai para o final da frase, como em 'ich komme heute an'.",
    "Regra rápida: no particípio passado de verbos separáveis, o ge- entra entre o prefixo e o verbo, como em angekommen.",
    "Regra rápida: verbos com prefixos inseparáveis, como be-, er-, ver- e ent-, não recebem ge- no particípio passado.",
    "Regra rápida: verbos terminados em -ieren, como studieren (estudar), não recebem ge- no particípio passado, ficando studiert.",
    "Regra rápida: no imperativo singular informal, o -e final costuma ser opcional, como em Komm(e)!, venha!",
    "Em alemão, alguns verbos fortes mudam a vogal na segunda e terceira pessoa do presente, como geben vira du gibst.",
    "Em alemão, lesen (ler) muda a vogal no presente: du liest, er liest, em vez de du lesst.",
    "Regra rápida: o futuro em alemão se forma com werden mais o infinitivo no final da frase.",
    "Regra rápida: o mais-que-perfeito em alemão se forma com hatte ou war mais o particípio passado.",
    "Em alemão, verbos reflexivos como sich freuen (alegrar-se) formam o tempo perfeito com haben, mesmo expressando um estado.",
    "Regra rápida: no Konjunktiv II, usado para hipóteses, sein vira wäre e haben vira hätte.",

    # --- Tenses (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: em alemão, o tempo presente costuma indicar também uma ação futura, sem precisar do verbo werden.",
    "Em alemão, para dizer que uma ação começou no passado e continua até agora, usa-se o tempo presente com seit, e não o perfeito como em português.",
    "Regra rápida: na fala, o alemão usa mais o tempo perfeito para narrar o passado, enquanto o passado simples predomina na escrita.",
    "Regra rápida: no sul da Alemanha, na Áustria e na Suíça, quase não se usa o passado simples na fala, prefere-se o perfeito.",
    "Em alemão, verbos como sein, haben e os modais continuam comuns no passado simples mesmo na fala, inclusive no norte da Alemanha.",
    "Regra rápida: o tempo perfeito em alemão costuma indicar uma ação passada que ainda tem efeito no presente.",
    "Em alemão, as palavras schon (já) e noch nicht (ainda não) combinam naturalmente com o tempo perfeito.",
    "Regra rápida: o chamado 'presente histórico' é usado em alemão para narrar fatos passados como se estivessem acontecendo agora.",
    "Regra rápida: o alemão não tem tempos verbais progressivos - 'ich lese' pode significar tanto 'eu leio' quanto 'eu estou lendo'.",
    "Em alemão, para deixar claro que uma ação está em andamento, usa-se advérbios como gerade ou eben, como em 'ich schreibe gerade einen Brief'.",
    "Regra rápida: na fala informal, a construção 'am' mais infinitivo substantivado expressa uma ação em progresso, como em 'er ist am Arbeiten'.",
    "Em alemão, o tempo futuro costuma expressar mais uma suposição ou previsão do que uma certeza sobre o futuro.",
    "Regra rápida: o mais-que-perfeito em alemão indica uma ação que aconteceu antes de outra ação passada, muito usado com a conjunção nachdem.",
    "Em alemão, diferente do português, não há uma diferença clara de sentido entre o passado simples e o perfeito - a escolha é mais uma questão de estilo.",
    "Regra rápida: a partícula wohl junto com o futuro expressa uma suposição, como em 'sie wird wohl zu Hause sein', ela deve estar em casa.",
    "Regra rápida: em orações com wenn referindo-se ao futuro, o alemão usa o tempo perfeito onde o português usaria o futuro.",
    "Em alemão, o presente do verbo kommen pode se referir a uma ação recém-concluída, como em 'ich komme, die Miete zu bezahlen', eu vim pagar o aluguel.",
    "Regra rápida: em manchetes de jornal e frases curtas, o alemão prefere o passado simples por soar mais direto.",
    "Em alemão, o passado simples também é chamado de Präteritum e apenas indica que algo aconteceu no passado, sem sugerir ação incompleta.",
    "Regra rápida: em alemão, o futuro composto com werden mais infinitivo passado expressa uma suposição sobre algo que já aconteceu.",

    # --- Modal auxiliaries (Hammer's German Grammar and Usage, 7th ed.) ---
    "Os seis verbos modais do alemão são: dürfen, können, mögen, müssen, sollen e wollen.",
    "Regra rápida: verbos modais em alemão são seguidos por um infinitivo 'puro', sem a partícula 'zu'.",
    "Regra rápida: com um verbo modal, o infinitivo do verbo principal vai para o final da frase, como em 'Ich kann gut schwimmen' - eu sei nadar bem.",
    "'Können' significa poder ou conseguir fazer algo, no sentido de capacidade.",
    "'Dürfen' significa ter permissão para algo - é o 'poder' de quem tem autorização.",
    "'Müssen' significa precisar ou ter que fazer algo, por necessidade.",
    "'Sollen' significa dever fazer algo, geralmente porque outra pessoa mandou ou pediu.",
    "'Wollen' significa simplesmente querer fazer algo.",
    "'Mögen' no presente costuma significar gostar de algo ou alguém: 'Ich mag dich' é 'eu gosto de você'.",
    "Regra rápida: 'nicht dürfen' significa que algo é proibido, como 'não pode' em português.",
    "Regra rápida: 'nicht müssen' não significa proibido, e sim que não é necessário - 'não precisa'.",
    "'Möchte', forma de 'mögen', é a maneira educada de dizer 'gostaria de': 'Ich möchte Kaffee' é 'eu gostaria de um café'.",
    "'Können' também pode significar saber algo, como um idioma: 'Er kann Spanisch' é 'ele sabe espanhol'.",
    "Curiosidade: em alemão dá para usar dois verbos modais na mesma frase, o que o português normalmente evita.",
    "Regra rápida: no passado composto, um verbo modal usa o infinitivo no lugar do particípio quando vem acompanhado de outro verbo.",
    "'Sollen' costuma indicar uma obrigação imposta por outra pessoa, diferente de 'müssen', que é uma necessidade da própria pessoa.",
    "'Sollen' também é usado para boatos: 'Er soll reich sein' significa algo como 'dizem que ele é rico'.",
    "A forma 'dürfte' (de 'dürfen') expressa uma suposição, tipo 'provavelmente': 'Das dürfte reichen' é 'isso provavelmente é suficiente'.",
    "A forma 'könnte' (de 'können') expressa uma possibilidade mais remota, como 'poderia' em português.",
    "'Mögen' seguido de infinitivo quase só é usado em frases negativas, como 'Ich mag das nicht tun' - eu não quero fazer isso.",
    "'Müssen' também pode expressar uma conclusão lógica, como 'deve ser' em português: 'Das muss ein Fehler sein' é 'isso deve ser um erro'.",
    "Um verbo de movimento pode ser omitido depois de um modal quando a direção já está clara: 'Ich will nach Frankfurt' é 'eu quero ir para Frankfurt'.",
    "'Wollen' usado sozinho, sem infinitivo, também funciona como verbo completo: 'Was willst du?' é 'o que você quer?'.",
    "Regra rápida: verbos modais em alemão têm todos os tempos verbais, diferente do inglês - existe até um futuro de 'können'.",

    # --- Word order (Hammer's German Grammar and Usage, 7th ed.) ---
    "Regra rápida: em alemão, só um elemento pode vir antes do verbo conjugado na oração principal - e não precisa ser o sujeito.",
    "Em perguntas de sim ou não e em ordens, o verbo conjugado vem em primeiro lugar, como em 'Kommst du?' - você vem?",
    "Regra rápida: em orações subordinadas, como as que começam com 'dass', 'weil' ou 'ob', o verbo conjugado vai para o final.",
    "Exemplo com 'weil' (porque): em 'weil ich krank bin', o verbo 'bin' vai para o fim da oração.",
    "Em alemão, particípios, infinitivos e prefixos separáveis ficam no final da oração principal, formando o chamado 'colchete verbal'.",
    "Regra rápida: pronomes átonos, como 'ihn' ou 'mir', vêm logo depois do verbo conjugado, antes dos substantivos.",
    "A ordem normal dos pronomes em alemão é: primeiro o nominativo, depois o acusativo, depois o dativo.",
    "O pronome reflexivo 'sich' geralmente fica logo depois do verbo conjugado, na mesma posição dos outros pronomes.",
    "Regra rápida: em alemão, quase qualquer elemento pode abrir a frase para dar ênfase, mas o verbo sempre fica na segunda posição.",
    "Quando 'nicht' nega a frase inteira, ele fica quase no final, antes dos complementos e advérbios de modo.",
    "Quando 'nicht' nega só uma palavra específica, ele vem logo antes dela, não no final da frase.",
    "Exemplo: 'Ich komme nicht' nega a frase toda, mas 'Ich komme nicht heute' nega só a palavra 'hoje'.",
    "Complementos como lugares e objetos com preposição ficam bem no final da oração, logo antes do último verbo.",
    "Curiosidade: ao contrário da regra tradicional de 'tempo-modo-lugar', a ordem real dos advérbios em alemão costuma ser tempo-lugar-modo.",
    "Regra rápida: quando dois verbos aparecem juntos no final de uma oração, tipo 'schwimmen gelernt', o verbo principal vem antes do auxiliar.",
    "Objetos no dativo geralmente vêm antes de objetos no acusativo, quando os dois são substantivos.",
    "Advérbios de tempo curtos, como 'heute' e 'gestern', costumam vir logo depois dos pronomes, bem no início da frase.",
    "Em orações principais ligadas por 'und', 'aber' ou 'oder', o verbo continua na segunda posição em cada uma delas.",
    "Regra rápida: o elemento colocado mais perto do final da frase costuma carregar a informação mais importante.",
    "Interjeições como 'Ach', 'Ja' e 'Nein' ficam fora da regra do verbo em segunda posição - vêm antes, separadas por vírgula.",
    "Em orações com 'zu' mais infinitivo, o verbo também vai para o final, assim como nas orações subordinadas.",
    "Regra rápida: em alemão é a terminação das palavras, não a ordem, que mostra quem é sujeito e quem é objeto na frase.",

    # --- Palavras mais usadas: substantivos (Preply) ---
    "Em alemão, 'Beispiel' significa exemplo.",
    "Em alemão, 'Jahr' significa ano.",
    "Em alemão, 'Morgen' significa manhã.",
    "Em alemão, 'Stadt' significa cidade.",

    # --- Palavras mais usadas: possessivos (Preply) ---
    "Em alemão, 'mein' significa meu.",
    "Em alemão, 'dein' significa teu, no sentido informal.",
    "Cuidado: em alemão, 'sein' pode significar tanto o verbo ser/estar quanto o possessivo 'dele', dependendo do contexto.",
    "Em alemão, 'ihr' pode significar 'dela' ou 'vocês', e com maiúscula, 'Ihr' é 'de vocês' no tratamento formal.",
    "Em alemão, 'unser' significa nosso.",
    "Em alemão, 'euer' significa 'de vocês', no plural informal.",

    # --- Palavras mais usadas: outros pronomes (Preply) ---
    "Em alemão, 'dieser', 'diese' e 'dieses' significam 'este' ou 'esse', mudando conforme o gênero.",
    "Em alemão, 'mehr' significa mais.",
    "Em alemão, 'man' significa 'a gente' ou 'as pessoas em geral', tipo o 'se' impessoal do português.",
    "Em alemão, 'nichts' significa nada.",

    # --- Palavras mais usadas: adjetivos (Preply) ---
    "Em alemão, 'lang' significa longo.",
    "Em alemão, 'neu' significa novo.",
    "Em alemão, 'alt' significa velho ou antigo.",
    "Em alemão, 'viel' significa muito.",
    "Em alemão, 'groß' significa grande ou alto.",
    "Em alemão, 'klein' significa pequeno.",
    "Em alemão, 'ganz' significa todo, completo ou inteiro.",
    "Em alemão, 'andere' significa outro ou outra.",

    # --- Palavras mais usadas: interrogativos (Preply) ---
    "Em alemão, 'wie' significa como.",
    "Em alemão, 'wo' significa onde.",
    "Em alemão, 'was' significa o que.",

    # --- Palavras mais usadas: verbos (Preply) ---
    "Em alemão, 'geben' significa dar.",
    "Em alemão, 'sagen' significa dizer.",
    "Em alemão, 'kommen' significa vir.",
    "Em alemão, 'wollen' significa querer.",
    "Em alemão, 'lassen' significa deixar ou permitir.",
    "Em alemão, 'wissen' significa saber.",
    "Em alemão, 'gehen' significa ir.",
    "Em alemão, 'machen' significa fazer.",

    # --- Palavras mais usadas: advérbios gerais (Preply) ---
    "Em alemão, 'ja' significa sim.",
    "Em alemão, 'nein' significa não, quando usado sozinho pra responder uma pergunta.",
    "Em alemão, 'auch' significa também.",
    "Em alemão, 'so' pode significar 'então' ou 'assim'.",
    "Em alemão, 'etwa' significa 'cerca de' ou 'aproximadamente'.",
    "Em alemão, 'vielleicht' significa talvez.",
    "Em alemão, 'kaum' significa 'quase não' ou 'dificilmente'.",
    "Em alemão, 'doch' pode significar 'mas', ou reforçar uma resposta contrária ao que foi perguntado.",
    "Em alemão, 'nur' significa apenas ou só.",

    # --- Palavras mais usadas: advérbios de lugar (Preply) ---
    "Em alemão, 'hier' significa aqui.",
    "Em alemão, 'oben' significa em cima ou lá em cima.",
    "Em alemão, 'unten' significa embaixo.",
    "Em alemão, 'da' pode significar 'lá' ou 'então', dependendo do contexto.",

    # --- Palavras mais usadas: advérbios de tempo (Preply) ---
    "Em alemão, 'dann' significa então, no sentido de sequência de tempo.",
    "Em alemão, 'wieder' significa de novo.",
    "Em alemão, 'noch' significa ainda.",
    "Em alemão, 'schon' significa já.",
    "Em alemão, 'jetzt' significa agora.",
    "Em alemão, 'immer' significa sempre.",

    # --- Palavras mais usadas: preposições (Preply) ---
    "Em alemão, 'mit' significa com.",
    "Em alemão, 'zu' significa 'para' ou 'em direção a'.",
    "Em alemão, 'in' significa 'dentro de' ou 'em'.",
    "Em alemão, 'unter' significa embaixo de.",
    "Em alemão, 'auf' significa 'sobre' ou 'em cima de'.",
    "Em alemão, 'für' significa para.",
    "Em alemão, 'von' significa 'de', geralmente indicando posse ou origem.",
    "Em alemão, 'an' significa 'em' ou 'junto a', tipo perto de uma superfície vertical.",
]
